GET http://localhost:3001/users/
GET http://localhost:3001/users/admin
GET http://localhost:3001/users/admin/active
GET http://localhost:3001/users/admin/?order=asc&limit=10&page=1
GET http://localhost:3001/tasks/admin
GET http://localhost:3001/some.text
GET http://localhost:3001/post
GET http://localhost:3001/posts
GET http://localhost:3001/tag
GET http://localhost:3001/tags
GET http://localhost:3001/taging
GET http://localhost:3001/error/404
GET http://localhost:3001/error/403
GET http://localhost:3001/butterfly
GET http://localhost:3001/housefly
GET http://localhost:3001/firefly
GET http://localhost:3001/fly
GET http://localhost:3001/flying

